image folder: "./resource/ACNE04/Classification/JPEGImages/"
label: {
  0: 0, 
  1: 1, 
  2: 1, 
  3: 1
}
train: {
  table: "./resource/ACNE04/Classification/NNEW_train_0.csv",
  data structure: "./resource/ACNE04/Extraction/train.pkl"
}
validation: {
  table: "./resource/ACNE04/Classification/NNEW_val_0.csv",
  data structure: "./resource/ACNE04/Extraction/validation.pkl"
}
test: {
  table: "./resource/ACNE04/Classification/NNEW_test_0.csv",
  data structure: "./resource/ACNE04/Extraction/test.pkl"
}