image: "./resource/ACNE04/Classification/JPEGImages/"
label: {
  0: 0, 
  1: 1, 
  2: 1, 
  3: 1
}
attribution: {
  table: './resource/ACNE04/attribution.csv'
}
train: {
  table: "./resource/ACNE04/Classification/NNEW_train_0.csv",
  dictionary: "./resource/ACNE04/v1/train.pkl"
}
validation: {
  table: "./resource/ACNE04/Classification/NNEW_val_0.csv",
  dictionary: "./resource/ACNE04/v1/validation.pkl"
}
test: {
  table: "./resource/ACNE04/Classification/NNEW_test_0.csv",
  dictionary: "./resource/ACNE04/v1/test.pkl"
}
