
label : {'lower':0, 'higher':1}
storage : "./resource/v2(ASKiN)/jpg/*/"
embedding : [
  'partition_臉頰區域', 'partition_額頭區域','partition_嘴巴、下巴區域', 'partition_鼻子區域', 'partition_我不確定',
  'howlong_三個月以上', 'howlong_三個月以下', 
  'squeeze_沒有', 'squeeze_有', 
  'cream_沒有', 'cream_有，藥局購買的外用藥', 'cream_有，醫師開立的外用藥', 'cream_有，非藥用抗痘產品', 
  'medicine_否', 'medicine_是', 
  'menstruation_性別男性跳過', 'menstruation_是', 'menstruation_我不確定', 'menstruation_否', 
  'age_26-40歲', 'age_19-25歲', 'age_18歲以下', 'age_41-50歲', 'age_51歲以上', 
  'sex_女性', 'sex_男性', 'sex_不想回答'
]
