
storage: './resource/ACNE04/Classification/JPEGImages/'
label: {0: 0, 1: 1, 2: 1, 3: 1},
train: {
  # storage: './resource/ACNE04/Classification/JPEGImages/',
  table: './resource/ACNE04/Classification/NNEW_trainval_0.csv',
  # 'label': {0: 0, 1: 1, 2: 1, 3: 1},
  pickle: './resource/ACNE04/Attribution/train.pkl'
}

test: {
  # storage: './resource/ACNE04/Classification/JPEGImages/',
  table: './resource/ACNE04/Classification/NNEW_test_0.csv',
  # label: {0: 0, 1: 1, 2: 1, 3: 1},
  pickle: './resource/ACNE04/Attribution/test.pkl'
}


# table: {
#   'train': './resource/ACNE04/Classification/NNEW_trainval_0.csv',
#   'validation': '',
#   'test': './resource/ACNE04/Classification/NNEW_test_0.csv',
# }
# storage: {"image": './resource/ACNE04/Classification/JPEGImages/'}
# label: {
#   0: 0, 1: 1, 2: 1, 3: 1
# }

# attribution: {
#   'train': './resource/ACNE04/Attribution/train.pkl',
#   "validation": './resource/ACNE04/Attribution/validation.pkl',
#   'test': './resource/ACNE04/Attribution/test.pkl'
# }

