storage: './resource/ACNE04/Classification/JPEGImages/'
label: {
  0: 0, 1: 1, 2: 1, 3: 1
}
attribution: {
  'train': './resource/ACNE04/Attribution/train.pkl',
  "validation": './resource/ACNE04/Attribution/validation.pkl',
  'test': './resource/ACNE04/Attribution/test.pkl'
}

