
storage: './resource/ACNE04/Classification/JPEGImages/'
label: {0: 0, 1: 1, 2: 1, 3: 1}
train: './resource/ACNE04/Classification/NNEW_trainval_0.csv'
validation: NULL
test: './resource/ACNE04/Classification/NNEW_test_0.csv'


